# Generated by Django 2.1 on 2021-04-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docentrada',
        ),
        migrations.DeleteModel(
            name='Inconsistencia',
        ),
    ]
